# Generated by Codex on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(
                choices=[
                    ('sport', 'Esporte'),
                    ('tourism', 'Turismo'),
                    ('health', 'Saúde'),
                    ('other', 'Outros'),
                ],
                default='other',
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(
                choices=[
                    ('joao-pessoa', 'João Pessoa'),
                    ('cabedelo', 'Cabedelo'),
                ],
                default='joao-pessoa',
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(
                choices=[
                    ('product', 'Produto'),
                    ('service', 'Serviço'),
                ],
                default='product',
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
