# Generated by Codex on 2026-04-21

from decimal import Decimal

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_item_type_category_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cashback_percentage',
            field=models.DecimalField(
                decimal_places=2,
                default=5,
                help_text='Percentual de cashback aplicado ao anuncio.',
                max_digits=5,
                validators=[MinValueValidator(Decimal('0')), MaxValueValidator(Decimal('100'))],
            ),
            preserve_default=False,
        ),
    ]
