# Generated by Django 5.2.13 on 2026-04-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Comprador'), ('seller', 'Vendedor')], default='buyer', max_length=10),
        ),
    ]
